api-version: '1.19'

# Change all of these to your plugin's information
name: ExamplePlugin
version: '0.1.0'
main: org.example.plugin.ExamplePlugin
description: Paper Example Plugin
authors: [You, Me]
libraries:
  - "de.miraculixx:kpaper:1.1.0"
